language: swift
osx_image: xcode8.3
sudo: false

script:
  - xcodebuild -scheme TvCodeScreen -workspace TvCodeScreen.xcworkspace -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p' build test 

after_success:
  - bash <(curl -s https://codecov.io/bash)

